// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMp6qFWN1t8uNAu1v4VhOq9kOsQt5dMik',
    appId: '1:132457464373:web:9c10d4e431d9e050c9a77c',
    messagingSenderId: '132457464373',
    projectId: 'tasks-ffcd8',
    authDomain: 'tasks-ffcd8.firebaseapp.com',
    storageBucket: 'tasks-ffcd8.appspot.com',
    measurementId: 'G-5Y3H1WFW0F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtuq17EXA34KD_Fn9tb-JAihYH3UOLq7Q',
    appId: '1:132457464373:android:436d35b41ae80955c9a77c',
    messagingSenderId: '132457464373',
    projectId: 'tasks-ffcd8',
    storageBucket: 'tasks-ffcd8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAE9jQgnK_7QZqY9vMHvUEJVU_hgDRVy1Q',
    appId: '1:132457464373:ios:111d9a4154ca04e5c9a77c',
    messagingSenderId: '132457464373',
    projectId: 'tasks-ffcd8',
    storageBucket: 'tasks-ffcd8.appspot.com',
    iosBundleId: 'com.example.todolistApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAE9jQgnK_7QZqY9vMHvUEJVU_hgDRVy1Q',
    appId: '1:132457464373:ios:56c56e3041ae9c5ac9a77c',
    messagingSenderId: '132457464373',
    projectId: 'tasks-ffcd8',
    storageBucket: 'tasks-ffcd8.appspot.com',
    iosBundleId: 'com.example.todolistApp.RunnerTests',
  );
}
